repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: '.travis.yml'
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
  - repo: https://gitlab.com/pycqa/flake8
    rev: "master" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        additional_dependencies: [flake8-import-order, flake8-bugbear]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
  - repo: local
    hooks:
      - id: update-ci
        name: Update CI jobs definitions
        description: Ensures that CI jobs definition are up to date.
        entry: scripts/make_ci_conf.py
        files: |
            (?x)^(
                scripts/make_ci_conf.py|
                .builds/test.*\.yaml|
            )$
        stages: [commit]
        language: script
